// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOsOiU3srEOC7iTZteqNkT4iJ-8nCRqK8',
    appId: '1:61052640074:web:ca3841f0f04a409c593fb3',
    messagingSenderId: '61052640074',
    projectId: 'chat-app-ce5de',
    authDomain: 'chat-app-ce5de.firebaseapp.com',
    storageBucket: 'chat-app-ce5de.firebasestorage.app',
    measurementId: 'G-VQMK6CXE4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB5GyiaPauhJIFkXR5y28QgZqcT_7DvH0',
    appId: '1:61052640074:android:ee0456f951e8d93e593fb3',
    messagingSenderId: '61052640074',
    projectId: 'chat-app-ce5de',
    storageBucket: 'chat-app-ce5de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5w0MmBoVgwHNK7vTkNQL8YFsy4U-nnCc',
    appId: '1:61052640074:ios:1dab9fe4548f4cec593fb3',
    messagingSenderId: '61052640074',
    projectId: 'chat-app-ce5de',
    storageBucket: 'chat-app-ce5de.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5w0MmBoVgwHNK7vTkNQL8YFsy4U-nnCc',
    appId: '1:61052640074:ios:1dab9fe4548f4cec593fb3',
    messagingSenderId: '61052640074',
    projectId: 'chat-app-ce5de',
    storageBucket: 'chat-app-ce5de.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOsOiU3srEOC7iTZteqNkT4iJ-8nCRqK8',
    appId: '1:61052640074:web:3995af68a454b9dd593fb3',
    messagingSenderId: '61052640074',
    projectId: 'chat-app-ce5de',
    authDomain: 'chat-app-ce5de.firebaseapp.com',
    storageBucket: 'chat-app-ce5de.firebasestorage.app',
    measurementId: 'G-C97W358BWC',
  );
}
